# Generated by Django 2.2.9 on 2020-02-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contemp_topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contemp_topics.Line'),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contemp_topics.Point'),
        ),
        migrations.AlterField(
            model_name='event',
            name='polygons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contemp_topics.Polygon'),
        ),
    ]
